### ISSUE TITLE
Auto map keys

### ISSUE THREAD

**Issue by MrRocket** [sinshu/managed-doom#14] opened 2021-07-13 19:01 UTC
I'm not sure if this has to do with a typical US keyboard layout or it's just my layout..
This is on a wireless Logitech keyboard/mouse combo.

I could zoom in but I couldn't zoom out.
In the AutoMap.cs I did this locally and it fixed it:

```
            // if (e.Key == DoomKey.Add || e.Key == DoomKey.Quote)
            if (e.Key == DoomKey.Equal || e.Key == DoomKey.Quote)
```
and
```
            // else if (e.Key == DoomKey.Subtract || e.Key == DoomKey.Hyphen)
            else if (e.Key == DoomKey.Semicolon || e.Key == DoomKey.Hyphen)
```

Otherwise, I think I would have to be pressing Shift also, at least on this keyboard. :\
Or was this intentional? heh

**Comment by sinshu** [comment] 2021-07-14 06:50
My keyboard is a Japanese layout, so I cannot tell much about this issue.
On my machine, the current automap implementation behaves in the same way as other famous ports.

Does your change make the automap behave in the same way as other ports on your machine?
If so, accepting all the following keys should solve the problem.

Zoom in:
* DoomKey.Add
* DoomKey.Quote
* DoomKey.Equal

Zoom out:
* DoomKey.Subtract
* DoomKey.Hyphen
* DoomKey.Semicolon

**Comment by MrRocket** [comment] 2021-07-14 16:02
> Does your change make the automap behave in the same way as other ports on your machine?

Yes actually, as well as the original Doom via Dosbox.

I also noticed that the Window size in DoomApplication.cs wouldn't allow me to make the window larger, only smaller.
So adding .Equal and .Semicolon to the case selection there fixes this also. ~ around lines 406 and 422 of DoomApplication.cs.

**Comment by sinshu** [comment] 2021-07-15 12:40
Could you check the PR above to confirm the problem is solved on your machine?

**Comment by MrRocket** [comment] 2021-07-15 17:36
Yes, that fixed both issues. :)

**Comment by sinshu** [comment] 2021-07-16 01:39
I merged the PR.
Thanks!

**Closed by sinshu** 2021-07-16 01:39 UTC
